SELECT * FROM customer limit 20

--1.What is the total revenue generated by male vs. female customers
SELECT gender, SUM(purchase_amount) as revenue
FROM customer
group by gender

--2.Which customer used a discount but still spent more than avg purchase amount
SELECT customer_id, purchase_amount
from customer
where discount_applied='Yes' and purchase_amount>=(select AVG(purchase_amount) from customer)

--3.Which are the top 5 products with the highest avg review rating?
SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc 
limit 5;

--Compare the average Purchase amounts between standard  express shipping
SELECT shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Do subscribed customers spend more? Compare avg spend & total revenue between subscribers & non-subscribers
SELECT subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
FROM customer
group by subscription_status
order by total_revenue, avg_spend desc;

--Which 5 products have the highest % of purchases with discounts applied?
SELECT item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;
--Segment customers into new, returning & loyal based on their total num of previous purchases & show count of each seg
with customer_type as (
select customer_id, previous_purchases,
CASE 
    WHEN previous_purchases=1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer
)
select customer_segment, count(*) as "Number of customers"
from customer_type
group by customer_segment

--What are the top 3 most purchased products within each category?
with item_count as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_count
where item_rank<=3;

--9)Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status

--What is the revenue contribution of each age group?
SELECT age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;




